name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3    
      - name: Set Docker Env
        uses: docker/setup-buildx-action@v2
      - name: Build Docker Image and Push if needed
        uses: docker/build-push-action@v4
        with:
          context: .
          file: "Dockerfile"
          tags: mydockertest:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
      - name: Run DockerContainer
        uses: addnab/docker-run-action@v3
        with:
          image: mydockertest:latest
          run: mvn clean test -DargLine="-Dkarate.env=test" "-Dkarate.options=--tags @smoke"
