name: QA - Manual Run

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run:  mvn clean test -DargLine="-Dkarate.env=test" "-Dkarate.options=--tags @smoke" --file pom.xml
      
    - name: Copy Test Results
      if: always()
      run: |
          mkdir -p resultsFolder
          pwd
          ls
          mv /home/runner/work/karateFrm_sample/karateFrm_sample/target* resultsFolder

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
         name: RunReports
         path: resultsFolder
